### ISSUE TITLE
under data store--"please add your data"--I think this actually requires 'write' permissions

### ISSUE THREAD

**Issue by amcooksey** [LegumeFederation/legfed-django-site#24]
I don't think that users can add data to the CyVerse data store as of now. Should we direct them to the 'contact us' form when they want to add data?

There are also the naming and file format specs that we require...

**Comment by adf-ncgr** [comment]
I agree. Started revising, but now blocked by #25

**Comment by adf-ncgr** [comment]
no longer blocked, and I believe it's fixed per the suggestion so closing
