### ISSUE TITLE
species five letter "gensp" abbreviation: autogeneration should be overrideable

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed-django-site#26]
Just in case we have collisions : 
Vigna monantha   = Vigmo
Vigna monophylla  = ?

or other factors (Pisum sativa ?) causing us to want to deviate from the norm.

we might just want to make this a field in Species

**Comment by svengato** [comment]
Will the abbreviation always be five letters? If not, how long can they be?

**Comment by ekcannon** [comment]
It looks like 5 character names are preferred, but that this is not a hard-and-fast rule. See:
https://www.uniprot.org/help/taxonomy
https://www.uniprot.org/docs/speclist

It will be challenging to stay current with UniProt, especially as there are at least 80 Archis species, most of which need stock records, which in turn require organism records and therefore, abbreviations. Creating unique 5-letter abbreviations for all of these these has not been particularly easy.

Looks like we will need to make rules about when to deviate from UniProt identifiers.

**Comment by adf-ncgr** [comment]
good question; roughly speaking, the inspiration for this comes from
https://www.uniprot.org/docs/speclist
though we don't actually follow it in all regards, e.g. we don't believe that:
GLYMA E  175778: N=Glyptosternon maculatum
                 C=Catfish
                 S=Parexostoma maculatum
or conversely,
SOYBN E    3847: N=Glycine max
                 C=Soybean
                 S=Glycine hispida

I guess there's probably nothing sacred about the number of letters being 5, but letting it get much longer than that would probably defeat the purpose.

**Comment by svengato** [comment]
Implemented. The species abbreviation can be up to 8 letters.
