### ISSUE TITLE
Landing page for ZBrowse

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed-django-site#29]
before linking from the site, we should provide some guidance, a landing page with some instructions, ala what GCV provides.

**Comment by adf-ncgr** [comment]
and for the benefit of those tasked with thinking about what should go on the landing page, here is the live version: https://www.legumefederation.org/shiny/ZBrowse/

**Comment by svengato** [comment]
I added a first cut at the ZBrowse landing page to the development site about a month ago,
http://dev.lis.ncgr.org:50003/en/zbrowse/
It is linked from both the Tools page and resource_mgr/tools.

**Comment by adf-ncgr** [comment]
The ZBrowse has landed. closing
