### ISSUE TITLE
Publishing a blog post without an author listed

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/legfed-django-site#32]
I want to post a blog post and leave the author field empty. I did not write the blog I am just posting it for the author (Nevin). 

I was able to do this on dev - publish a blog without an author. But I can not do the same on production. 
![Screen Shot 2019-06-25 at 2 07 26 PM](https://user-images.githubusercontent.com/13021601/60126069-cd5c4700-9752-11e9-9d83-d839146ba518.png)

**Comment by adf-ncgr** [comment]
OK, I think this is fixed (tweak to blog config to not set author by default). close when verified...

**Comment by jd-campbell** [comment]
THANKS!
