### ISSUE TITLE
intermine template error (phytomine)

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed-django-site#33]
The phytomine templates appear dynamically as expected, but the first one I happened to try to use gave me an error (the second one I tried worked, so it is not interaction with phytomine per se but something about the way the query is being constructed- it is a relatively complex template so probably not surprising):

Expression of gene homologs in Arabidopsis :
The RNA-seq expression in Arabidopsis Gene Atlas experiments for homologs of a given gene or list of genes) 

Request Method: | GET
-- | --
http://dev.lis.ncgr.org:50003/en/intermine_mgr/templates/constraints/?q=rna-seq-homologs_1__Phytomine%20(The%20Mother%20of%20all%20Plant%20Mines)&opA==&valueA=At1g34500&opB==&valueB=A.%20thaliana&opC=CONTAINS&valueC=GeneAtlas&rows=25
1.11.20
ConstraintError
"There is a constraint 'B' on this query, but it is not editable"
/home/svengato/legfed-django-site/env/lib/python3.6/site-packages/intermine/query.py in get_adjusted_template, line 1808

**Comment by svengato** [comment]
It now detects and prevents changes to constraints that are -not- editable.
