### ISSUE TITLE
develop a better way of handling content updates than hand-crafted pages for some of the key pages

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/legfed-django-site#5]
for example, IMHO adding a species (or adding info a species) should not take place by editing the page http://fisher.ncgr.org:50000/en/species/

rather, we should have a content model for a species that drives generation of such a page; I'm guessing one of the major use cases is "I have a new URL that users interested in <datatype X> for species <A,B,C> should be able to find". Rather than having someone add links to species and tools for this, we should have the person adding the new URL categorize it with respect to the suitable dimensions and policy for where this appears on the site then takes over. 

this would be sort of along the lines of the way spreadsheets are used to structure info about species behind the scenes at LIS, then transformed into the contents of the species overview page; but rather than spreadsheets, the django db would hold the data model. 

Maybe not for the initial release of the site, but perhaps someone will take the initiative and make it happen behind my back (though probably should be discussed among content managers first). Already discussed briefly with @sammyjava

**Comment by sammyjava** [comment]
Note: requires python/django skillz.

**Comment by adf-ncgr** [comment]
will require such skillz to get implemented, but presumably once implemented the skillzless will have the power (harnessed by the structure of the forms) to add content through the implemented plugin. right?

**Comment by adf-ncgr** [comment]
another area we might want to use this is for the "Announcements"
just glancing at the nascent home page, I see that 2 out of 3 of the conferences listed there are past.
Of course, this is because no one has been paying any attention, but similar to what I proposed above it seems like taking a somewhat structured approach would allow us to display only upcoming events without having to perpetually modify that section of the page. Probably there are even some existing plugins for this sort of thing.

**Comment by adf-ncgr** [comment]
I think I will close this since we've more or less developed the envisioned better way (hopefully we keep thinking it is indeed better); we can open a new issue for Tools when we are ready to tackle it
